/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sr.com.view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sr.com.pojo.Sales;
import sr.com.service.CommonService;
import sr.com.serviceImpl.SalesServiceImpl;
import sr.com.utils.CommonMenu;
import sr.com.utils.UserMenu;

/**
 *
 * @author User
 */
public class SalesReport1 extends javax.swing.JFrame {
    CommonService commonService= new SalesServiceImpl();
    /**
     * Creates new form SalesReport
     */
    public SalesReport1() {
        initComponents();
        displaySalesData();
        totalSalesAmount();
        this.setExtendedState(MAXIMIZED_BOTH);
        UserMenu commonMenu=new UserMenu();
        commonMenu.getCommonMenu(this);
        
       
    }
public void displaySalesData(){
    DefaultTableModel model= (DefaultTableModel) tblDisplay.getModel();
    model.setRowCount(0);
    Object[] row = new Object[5];
    List<Sales> list=commonService.getList();
    for(int i = 0; i<list.size(); i++){
        row[0]=list.get(i).getId();
        row[1]=list.get(i).getCustomerName();
        row[2]=list.get(i).getMobile();
        row[3]=list.get(i).getTotalPrice();
        row[4]=list.get(i).getSalesDate();
        model.addRow(row);
    }
}
public void totalSalesAmount(){
    int x=0;
    for(int i=0; i < tblDisplay.getRowCount(); i++){
        x+=Double.parseDouble(tblDisplay.getValueAt(i, 3).toString());
    }
    lblTotalSales.setText("Total Sales:  "+x+"");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        lblTotalSales = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Costomer Name", "Mobile Number", "Total Price", "Sales Date"
            }
        ));
        jScrollPane1.setViewportView(tblDisplay);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 1340, 400);

        lblTotalSales.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblTotalSales.setForeground(new java.awt.Color(255, 0, 0));
        lblTotalSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTotalSales);
        lblTotalSales.setBounds(800, 220, 500, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Java\\JAVA\\MedicineShop\\photo\\Capture6.PNG")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 1370, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JTable tblDisplay;
    // End of variables declaration//GEN-END:variables
}
